<?php
return [
    // ... (El mismo código en inglés del mensaje anterior) ...
    // PDF Header
    'brand_name' => 'K-Hamburgesas',
    'daily_report_title' => 'Daily Cash Register Report',
    'operative_day' => 'Operative Day:',
    'issued_by' => 'Issued by:',
    
    // PDF Resumen
    'total_cash_flow' => 'Total Cash Flow',
    'successful_transactions' => 'Successful Transactions',
    
    // PDF Tabla Órdenes
    'transactions_breakdown' => 'Transactions Breakdown',
    'col_folio' => 'Order #',
    'col_time' => 'Time',
    'col_consumer' => 'Consumer',
    'col_method' => 'Method',
    'col_status' => 'Status',
    'col_amount' => 'Amount',
    'counter' => 'Counter',
    'no_financial_movements' => 'No financial movements in the period.',
    
    // PDF Tabla Auditoría
    'operative_audit' => 'Operative Audit and Exceptions',
    'col_verdict' => 'Verdict',
    'col_exception_detail' => 'Exception Detail',
    'col_authorized_by' => 'Authorized by',
    'col_requested_by' => 'Requested by',
    'no_exceptions' => 'No exceptions or cancellations were recorded during the day.',
    
    // PDF Footer
    'confidential_doc' => 'Confidential document for exclusive managerial use. Automatically generated by K-Admin System.',
    'date_format' => 'm/d/Y', 
    
    // CSV / EXCEL
    'csv_filename' => 'Sales_History_',
    'csv_col_id' => 'Order ID',
    'csv_col_date' => 'Date',
    'csv_col_time' => 'Time',
    'csv_col_type' => 'Order Type',
    'csv_col_client' => 'Client / Table',
    'csv_col_items' => 'Items Sold',
    'csv_col_total' => 'Total',
    'csv_col_method' => 'Payment Method',
    'csv_col_status' => 'Status',
    'csv_col_exceptions' => 'Exceptions / Canceled By',
    
    // Valores CSV
    'type_local' => 'Dine-in / Counter',
    'type_delivery' => 'Delivery / Takeout',
    'exception_none' => 'None',
    'exception_canceled_by' => 'Canceled by: ',
    'deleted_product' => 'Deleted Product',
    'no_details' => 'No details',
];